version: '3'
services:
  ranchers:
    image: rancher/rancher:v.2.8.2
    container_name: ranchers
    privileged: true
    volumes:
      - /opt/rancher:/var/lib/rancher
      - ${HOMEDIR}/certs/rancher:/var/lib/ca-certificates
    restart: always
    ports:
      - 443:443
      - 80:80
